version: '3.5'

services:
    configmanager-ui:
        image: configmanager-ui
        network_mode: host
        ports:
            - "8080:8080"
            - "8081:8081"
            - "8082:8082"
            - "80:80"
