version: '3.5'

services:
    configmanager-ui:
        image: configmanager-ui
        network_mode: host
        environment:
            - CONFIGMANAGER_HOST=localhost
            - CONFIGMANAGER_PORT=8081
            - UI_BACKEND_URL=http://localhost:80
        ports:
            - "8080:8080"
            - "8081:8081"
            - "8082:8082"
            - "80:80"
