version: '3.5'

services:
    dataspaceconnector-ui:
        image: dataspaceconnector-ui
        environment:
            - CONNECTOR_URL=https://localhost:8080
            - CONNECTOR_USER=admin
            - CONNECTOR_PASSWORD=password
        ports:
            - "8083:8083"
